"""
runner/pipeline.py
==================
AlgoTradingPipeline — the single orchestrator that wires together:

    trading_data      → fetch OHLCV data for benchmark + universe stocks
    market_regime     → classify the market-level regime from benchmark data
    stock_regime      → classify every stock using market context + stock data

The pipeline reads universe definitions from pipeline.yaml.  Symbols are
loaded dynamically from flat text files (one Yahoo Finance ticker per line)
generated by the scripts in scripts/.

    scripts/build_nifty500.py   →  data/universes/nifty500.txt
    scripts/build_sp500.py      →  data/universes/sp500.txt

No symbols are hardcoded in this file or in pipeline.yaml.

Call flow
---------
1. Load pipeline config (pipeline.yaml)
2. Build DataManager, MarketRegimeEngine, StockRegimeEngine
3. For each universe:
   a. Load symbol list from symbol_source file
   b. Fetch benchmark OHLCV
   c. Classify market regime
   d. Batch-fetch all stock OHLCV
   e. Classify stocks using market context
   f. Persist outputs

Usage
-----
    from runner.pipeline import AlgoTradingPipeline

    pipeline = AlgoTradingPipeline()
    output   = pipeline.run()

    # Single universe
    result = pipeline.run_single_universe("NIFTY500")

    # Quick test: only first 20 symbols
    output = pipeline.run(max_symbols=20)
"""

from __future__ import annotations

import logging
import sys
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from typing import Optional

import pandas as pd
import yaml

logger = logging.getLogger(__name__)

_DEFAULT_PIPELINE_CONFIG = Path(__file__).parent / "config" / "pipeline.yaml"


# ─────────────────────────────────────────────────────────────────────────────
#  Output containers
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class UniverseRunResult:
    """All outputs for a single universe from one pipeline run."""
    universe:       str
    market_regime:  dict                     # RegimeResult.to_dict()
    stock_results:  list                     # list[StockRegimeResult]
    failed_symbols: dict[str, str]           # {symbol: error_message}
    symbols_loaded: int   = 0               # how many tickers were in the file
    benchmark_df:   Optional[pd.DataFrame] = None
    run_date:       date  = field(default_factory=date.today)


@dataclass
class PipelineRunOutput:
    """Full output of one AlgoTradingPipeline.run() call."""
    market_results:   dict[str, dict]              = field(default_factory=dict)
    stock_results:    dict[str, list]              = field(default_factory=dict)
    universe_details: dict[str, UniverseRunResult] = field(default_factory=dict)
    run_date:         date                         = field(default_factory=date.today)
    elapsed_seconds:  float                        = 0.0


# ─────────────────────────────────────────────────────────────────────────────
#  Symbol file loader
# ─────────────────────────────────────────────────────────────────────────────

class SymbolFileLoader:
    """
    Loads ticker symbols from a flat text file (one ticker per line).

    File format
    -----------
    One Yahoo Finance ticker per line, UTF-8.
    Blank lines and lines starting with ``#`` are ignored.

    Example (data/universes/nifty500.txt)
    ------
    RELIANCE.NS
    TCS.NS
    INFY.NS
    # this line is a comment
    HDFCBANK.NS
    ...

    Parameters
    ----------
    project_root :
        Absolute path to the project root.  Relative ``symbol_source`` paths
        in pipeline.yaml are resolved against this.
    """

    def __init__(self, project_root: Path) -> None:
        self._root = project_root

    def load(
        self,
        symbol_source: str,
        max_symbols:   Optional[int] = None,
        allow_missing: bool = False,
    ) -> list[str]:
        """
        Read tickers from *symbol_source*.

        Parameters
        ----------
        symbol_source :
            Path to the text file.  Relative paths are resolved from the
            project root.
        max_symbols :
            When set, return only the first *max_symbols* tickers.
            Useful for quick test runs without changing config.
        allow_missing :
            When ``True``, return an empty list if the file does not exist
            and log a warning.  When ``False`` (default), raise
            ``FileNotFoundError`` with a helpful message.

        Returns
        -------
        list[str]
            Cleaned, non-empty ticker strings.
        """
        path = Path(symbol_source)
        if not path.is_absolute():
            path = self._root / path

        if not path.exists():
            msg = (
                f"Symbol file not found: '{path}'\n"
                f"Generate it by running:\n"
                f"  python scripts/build_nifty500.py    (for NIFTY 500)\n"
                f"  python scripts/build_sp500.py       (for S&P 500)"
            )
            if allow_missing:
                logger.warning(msg)
                return []
            raise FileNotFoundError(msg)

        tickers = self._parse_file(path)

        if not tickers:
            logger.warning("Symbol file '%s' is empty.", path)
            return []

        if max_symbols is not None:
            original_count = len(tickers)
            tickers = tickers[:max_symbols]
            logger.info(
                "max_symbols=%d applied: using %d of %d tickers from '%s'.",
                max_symbols, len(tickers), original_count, path.name,
            )
        else:
            logger.info(
                "Loaded %d tickers from '%s'.", len(tickers), path.name
            )

        return tickers

    @staticmethod
    def _parse_file(path: Path) -> list[str]:
        """Read, clean, and return tickers from a symbol file."""
        tickers: list[str] = []
        for raw_line in path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue                      # skip blank lines and comments
            tickers.append(line)
        return tickers


# ─────────────────────────────────────────────────────────────────────────────
#  Pipeline
# ─────────────────────────────────────────────────────────────────────────────

class AlgoTradingPipeline:
    """
    Orchestrates the full data → market regime → stock regime pipeline.

    Parameters
    ----------
    config_path :
        Path to pipeline.yaml.  Defaults to runner/config/pipeline.yaml.
    project_root :
        Absolute project root.  Symbol file paths are resolved from here.
        Defaults to the parent of the runner/ package.
    """

    def __init__(
        self,
        config_path:  Optional[Path] = None,
        project_root: Optional[Path] = None,
    ) -> None:
        self._root     = project_root or Path(__file__).parent.parent
        self._cfg_path = config_path  or _DEFAULT_PIPELINE_CONFIG
        self._cfg      = self._load_config(self._cfg_path)
        self._run_date = date.today()

        # Ensure project root is importable
        root_str = str(self._root)
        if root_str not in sys.path:
            sys.path.insert(0, root_str)

        self._setup_logging()
        self._build_engines()
        self._symbol_loader = SymbolFileLoader(project_root=self._root)

    # ──────────────────────────────────────────────────────────────────────────
    #  Public API
    # ──────────────────────────────────────────────────────────────────────────

    def run(
        self,
        universes:   Optional[list[str]] = None,
        run_date:    Optional[date]      = None,
        persist:     Optional[bool]      = None,
        max_symbols: Optional[int]       = None,
    ) -> PipelineRunOutput:
        """
        Execute the full pipeline.

        Parameters
        ----------
        universes :
            Subset of universe names from pipeline.yaml to run.
            Defaults to all configured universes.
        run_date :
            Override the run date used for output partitioning.
        persist :
            Override the ``output.persist`` setting from config.
        max_symbols :
            Override ``symbol_loading.max_symbols`` from config.
            Useful for quick test runs: ``pipeline.run(max_symbols=20)``.

        Returns
        -------
        PipelineRunOutput
        """
        import time
        t0 = time.time()

        self._run_date  = run_date or date.today()
        do_persist      = persist if persist is not None else self._cfg["output"]["persist"]

        # Resolve max_symbols: CLI arg > config > None
        sym_cfg = self._cfg.get("symbol_loading", {})
        effective_max = max_symbols if max_symbols is not None else sym_cfg.get("max_symbols")

        available = list(self._cfg["universes"].keys())
        targets   = universes or available

        unknown = set(targets) - set(available)
        if unknown:
            raise ValueError(
                f"Unknown universe(s): {unknown}.  Available: {available}"
            )

        output = PipelineRunOutput(run_date=self._run_date)

        logger.info("=" * 60)
        logger.info(
            "Pipeline run  date=%s  universes=%s  max_symbols=%s",
            self._run_date, targets, effective_max or "all",
        )
        logger.info("=" * 60)

        for universe_name in targets:
            universe_cfg = self._cfg["universes"][universe_name]
            result = self._run_universe(
                universe_name, universe_cfg, do_persist, effective_max, sym_cfg
            )
            output.market_results[universe_name]   = result.market_regime
            output.stock_results[universe_name]    = result.stock_results
            output.universe_details[universe_name] = result

        output.elapsed_seconds = round(time.time() - t0, 2)

        logger.info("=" * 60)
        logger.info("Pipeline complete in %.1fs", output.elapsed_seconds)
        self._log_summary(output)
        logger.info("=" * 60)

        return output

    def run_single_universe(
        self,
        universe_name: str,
        run_date:      Optional[date] = None,
        persist:       bool = True,
        max_symbols:   Optional[int] = None,
    ) -> UniverseRunResult:
        """
        Run the pipeline for a single universe.

        Parameters
        ----------
        universe_name :
            Must match a key in pipeline.yaml ``universes`` section.
        run_date :
            Override for output partitioning.
        persist :
            Write parquet outputs.
        max_symbols :
            Cap the number of symbols processed.

        Returns
        -------
        UniverseRunResult
        """
        output = self.run(
            universes=[universe_name],
            run_date=run_date,
            persist=persist,
            max_symbols=max_symbols,
        )
        return output.universe_details[universe_name]

    # ──────────────────────────────────────────────────────────────────────────
    #  Per-universe pipeline
    # ──────────────────────────────────────────────────────────────────────────

    def _run_universe(
        self,
        universe_name: str,
        universe_cfg:  dict,
        persist:       bool,
        max_symbols:   Optional[int],
        sym_cfg:       dict,
    ) -> UniverseRunResult:
        """Full pipeline for one universe."""
        benchmark_symbol = universe_cfg["benchmark"]
        symbol_source    = universe_cfg["symbol_source"]
        allow_missing    = sym_cfg.get("allow_missing_file", False)

        data_cfg = self._cfg["data"]
        start    = data_cfg["start_date"]
        end      = data_cfg["end_date"]
        if end == "today":
            end = self._run_date.strftime("%Y-%m-%d")

        logger.info("─" * 50)
        logger.info("Universe: %s  |  benchmark=%s", universe_name, benchmark_symbol)
        logger.info("─" * 50)

        # ── Step 1: Load symbol list from file ───────────────────────────
        symbols = self._symbol_loader.load(
            symbol_source,
            max_symbols=max_symbols,
            allow_missing=allow_missing,
        )

        logger.info(
            "Symbol file: '%s'  →  %d symbols to process",
            symbol_source, len(symbols),
        )

        failed_symbols: dict[str, str] = {}

        # ── Step 2: Fetch benchmark ──────────────────────────────────────
        benchmark_df = self._fetch_benchmark(benchmark_symbol, start, end)

        # ── Step 3: Market regime ────────────────────────────────────────
        market_result = self._classify_market(benchmark_df, benchmark_symbol)
        logger.info(
            "Market regime: %s  (confidence=%.2f)",
            market_result["regime"], market_result["confidence"],
        )

        if not symbols:
            logger.warning(
                "No symbols loaded for '%s' — skipping stock classification.",
                universe_name,
            )
            return UniverseRunResult(
                universe=universe_name,
                market_regime=market_result,
                stock_results=[],
                failed_symbols={},
                symbols_loaded=0,
                benchmark_df=benchmark_df,
                run_date=self._run_date,
            )

        # ── Step 4: Batch-fetch stock OHLCV ─────────────────────────────
        stock_data, fetch_errors = self._fetch_stocks(symbols, start, end)
        failed_symbols.update(fetch_errors)

        # ── Step 5: Classify stocks ──────────────────────────────────────
        from stock_regime.src.models import MarketRegimeInput
        market_ctx = MarketRegimeInput.from_dict(market_result)

        stock_results = self._stock_engine.analyze_universe(
            stock_data     = stock_data,
            market_regime  = market_ctx,
            benchmark_data = benchmark_df,
            market_label   = universe_name,
            run_date       = self._run_date,
            persist        = persist,
        )

        for r in stock_results:
            if not r.is_valid():
                failed_symbols[r.symbol] = r.error or "unknown error"

        if failed_symbols:
            logger.warning(
                "%d symbols failed: %s",
                len(failed_symbols), list(failed_symbols.keys())[:10],
            )

        return UniverseRunResult(
            universe=universe_name,
            market_regime=market_result,
            stock_results=stock_results,
            failed_symbols=failed_symbols,
            symbols_loaded=len(symbols),
            benchmark_df=benchmark_df,
            run_date=self._run_date,
        )

    # ──────────────────────────────────────────────────────────────────────────
    #  Data fetching helpers
    # ──────────────────────────────────────────────────────────────────────────

    def _fetch_benchmark(self, symbol: str, start: str, end: str) -> pd.DataFrame:
        logger.info("Fetching benchmark: %s  (%s → %s)", symbol, start, end)
        df = self._data_manager.get_daily_data(symbol, start=start, end=end)
        logger.info(
            "  %s: %d bars  (%s → %s)",
            symbol, len(df), df.index[0].date(), df.index[-1].date(),
        )
        return df

    def _fetch_stocks(
        self, symbols: list[str], start: str, end: str
    ) -> tuple[dict[str, pd.DataFrame], dict[str, str]]:
        logger.info("Batch-fetching %d stocks  (%s → %s) …", len(symbols), start, end)
        results   = self._data_manager.fetch_multiple_symbols(symbols, start=start, end=end)
        successful: dict[str, pd.DataFrame] = {}
        failed:     dict[str, str]          = {}
        cached_count = 0

        for sym, result in results.items():
            if result.success and not result.data.empty:
                successful[sym] = result.data
                if result.from_cache:
                    cached_count += 1
            else:
                failed[sym] = result.error or "empty data"

        logger.info(
            "  Fetched: %d OK  |  %d failed  |  %d from cache",
            len(successful), len(failed), cached_count,
        )
        return successful, failed

    def _classify_market(self, benchmark_df: pd.DataFrame, symbol: str) -> dict:
        result = self._market_engine.analyze(benchmark_df)
        logger.debug(
            "  %s market regime: %s (conf=%.2f)",
            symbol, result.regime.value, result.confidence,
        )
        return result.to_dict()

    # ──────────────────────────────────────────────────────────────────────────
    #  Initialisation
    # ──────────────────────────────────────────────────────────────────────────

    def _build_engines(self) -> None:
        from trading_data import DataManager, DataManagerConfig
        from market_regime.src import MarketRegimeEngine
        from stock_regime.src import StockRegimeEngine

        data_cfg   = self._cfg["data"]
        output_cfg = self._cfg["output"]

        self._data_manager = DataManager(
            config=DataManagerConfig(
                cache_enabled      = True,
                cache_dir          = data_cfg["cache_dir"],
                cache_max_age_days = data_cfg["cache_max_age_days"],
                retry_attempts     = data_cfg["retry_attempts"],
            )
        )
        logger.info("DataManager ready.")

        mr_config = self._cfg.get("market_regime_config")
        self._market_engine = MarketRegimeEngine(
            config_path=Path(mr_config) if mr_config else None
        )
        logger.info("MarketRegimeEngine ready.")

        sr_config = self._cfg.get("stock_regime_config")
        self._stock_engine = StockRegimeEngine(
            config_path=Path(sr_config) if sr_config else None,
            output_dir=output_cfg["root_dir"],
        )
        logger.info("StockRegimeEngine ready.")

    def _setup_logging(self) -> None:
        log_cfg   = self._cfg.get("output", {})
        log_dir   = log_cfg.get("log_dir", "output/logs")
        log_level = getattr(logging, log_cfg.get("log_level", "INFO").upper(), logging.INFO)
        from stock_regime.src.logging_config import configure_logging
        configure_logging(log_dir=log_dir, console_level=log_level)
        for name in ("runner", "market_regime", "trading_data", "stock_regime"):
            logging.getLogger(name).setLevel(log_level)

    @staticmethod
    def _load_config(path: Path) -> dict:
        if not path.exists():
            raise FileNotFoundError(f"Pipeline config not found: {path}")
        with open(path) as fh:
            return yaml.safe_load(fh)

    # ──────────────────────────────────────────────────────────────────────────
    #  Summary
    # ──────────────────────────────────────────────────────────────────────────

    @staticmethod
    def _log_summary(output: PipelineRunOutput) -> None:
        for universe, results in output.stock_results.items():
            mr = output.market_results.get(universe, {})
            detail = output.universe_details.get(universe)
            loaded = detail.symbols_loaded if detail else "?"
            failed = len(detail.failed_symbols) if detail else 0
            logger.info(
                "%-10s  market=%-14s (%.2f)  loaded=%s  classified=%d  failed=%d",
                universe, mr.get("regime", "N/A"), mr.get("confidence", 0.0),
                loaded, len(results), failed,
            )
            counts: dict[str, int] = {}
            for r in results:
                k = r.stock_regime.value
                counts[k] = counts.get(k, 0) + 1
            for regime, count in sorted(counts.items(), key=lambda x: -x[1]):
                logger.info("  %-18s %3d", regime, count)